/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChatBox: typeof import('./src/components/main/ChatBox.vue')['default']
    Header: typeof import('./src/components/header/index.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    InputBox: typeof import('./src/components/InputBox.vue')['default']
    Main: typeof import('./src/components/main/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/sidebar/index.vue')['default']
    ThemeIcon: typeof import('./src/components/ThemeIcon.vue')['default']
    WelComeBox: typeof import('./src/components/WelComeBox.vue')['default']
  }
}
